pricing:
  inputs: 
    spot_price: 100
    interest_rate: 0.05
    carry_rate: 0.05
    volatility: 0.15
    option_type: 'American'
  dimensions: 
    strikes: 
      - 90
      - 95
      - 100
      - 105
      - 110
    expirations:
      - 30
      - 60
      - 90
