valuation:
  style: 'American'
  type: 'OTM'
  output: 'Value'
  factors: 
    spot_price: 100
    interest_rate: 0.05
    carry_rate: 0.05
    volatility: 0.15
  dimensions: 
    strikes: 
      min: 90
      incr: 0.5
      max: 110
    expirations:
      min: 30
      incr: 30
      max: 300
