valuation:
  dimensions:
    expirations: {incr: 30, max: 100, min: 30}
    strikes: {incr: 0.5, max: 110.0, min: 90.0}
  factors: {carry_rate: 0.05, interest_rate: 0.05, spot_price: 100.0, volatility: 0.15}
  output: Vega
  style: American
  type: OTM
