valuation:
  dimensions:
    expirations: {incr: 1, max: 40, min: 20}
    strikes: {incr: 0.25, max: 15.0, min: 5.0}
  factors: {carry_rate: 7.5, interest_rate: 15.0, spot_price: 10.0, volatility: 500.0}
  output: Theta
  style: American
  type: OTM
